<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Divorce $model */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Divorces', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="divorce-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'district:ntext',
            'local_level:ntext',
            'ward:ntext',
            'reg_no:ntext',
            'reg_year:ntext',
            'reg_month:ntext',
            'reg_day:ntext',
            'ad_reg_year:ntext',
            'ad_reg_month:ntext',
            'ad_reg_day:ntext',
            'registrar_name:ntext',
            'marriage_year:ntext',
            'marriage_month:ntext',
            'marriage_day:ntext',
            'ad_marriage_year:ntext',
            'ad_marriage_month:ntext',
            'ad_marriage_day:ntext',
            'groom_fname:ntext',
            'groom_mname:ntext',
            'groom_lname:ntext',
            'groom_fname_eng:ntext',
            'groom_mname_eng:ntext',
            'groom_lname_eng:ntext',
            'g_birth_year:ntext',
            'g_birth_month:ntext',
            'g_birth_day:ntext',
            'ad_g_birth_year:ntext',
            'ad_g_birth_month:ntext',
            'ad_g_birth_day:ntext',
            'g_place_of_birth:ntext',
            'g_permanent_address:ntext',
            'g_education:ntext',
            'g_religion:ntext',
            'g_mother_tongue:ntext',
            'g_prev_marital_status:ntext',
            'g_ctz_no:ntext',
            'g_ctz_year:ntext',
            'g_ctz_month:ntext',
            'g_ctz_day:ntext',
            'ad_g_ctz_year:ntext',
            'ad_g_ctz_month:ntext',
            'ad_g_ctz_day:ntext',
            'g_ctz_district:ntext',
            'g_grand_fname:ntext',
            'g_grand_mname:ntext',
            'g_grand_lname:ntext',
            'g_grand_fname_eng:ntext',
            'g_grand_mname_eng:ntext',
            'g_grand_lname_eng:ntext',
            'g_father_fname:ntext',
            'g_father_mname:ntext',
            'g_father_lname:ntext',
            'g_father_fname_eng:ntext',
            'g_father_mname_eng:ntext',
            'g_father_lname_eng:ntext',
            'bride_fname:ntext',
            'bride_mname:ntext',
            'bride_lname:ntext',
            'bride_fname_eng:ntext',
            'bride_mname_eng:ntext',
            'bride_lname_eng:ntext',
            'b_birth_year:ntext',
            'b_birth_month:ntext',
            'b_birth_day:ntext',
            'ad_b_birth_year:ntext',
            'ad_b_birth_month:ntext',
            'ad_b_birth_day:ntext',
            'b_place_of_birth:ntext',
            'b_permanent_address:ntext',
            'b_education:ntext',
            'b_religion:ntext',
            'b_mother_tongue:ntext',
            'b_prev_marital_status:ntext',
            'b_ctz_no:ntext',
            'b_ctz_year:ntext',
            'b_ctz_month:ntext',
            'b_ctz_day:ntext',
            'ad_b_ctz_year:ntext',
            'ad_b_ctz_month:ntext',
            'ad_b_ctz_day:ntext',
            'b_ctz_district:ntext',
            'b_grand_fname:ntext',
            'b_grand_mname:ntext',
            'b_grand_lname:ntext',
            'b_grand_fname_eng:ntext',
            'b_grand_mname_eng:ntext',
            'b_grand_lname_eng:ntext',
            'b_father_fname:ntext',
            'b_father_mname:ntext',
            'b_father_lname:ntext',
            'b_father_fname_eng:ntext',
            'b_father_mname_eng:ntext',
            'b_father_lname_eng:ntext',
            'total_child',
            'living_child',
            'with_father',
            'with_mother',
            'inf_fname:ntext',
            'inf_mname:ntext',
            'inf_lname:ntext',
            'inf_fname_eng:ntext',
            'inf_mname_eng:ntext',
            'inf_lname_eng:ntext',
            'inf_ctz_no:ntext',
            'inf_ctz_year:ntext',
            'inf_ctz_month:ntext',
            'inf_ctz_day:ntext',
            'ad_inf_ctz_year:ntext',
            'ad_inf_ctz_month:ntext',
            'ad_inf_ctz_day:ntext',
            'inf_ctz_district:ntext',
            'court_address:ntext',
            'court_name:ntext',
            'decison_year:ntext',
            'decison_month:ntext',
            'decision_day:ntext',
            'ad_decison_year:ntext',
            'ad_decison_month:ntext',
            'ad_decision_day:ntext',
            'di_scanned_image',
        ],
    ]) ?>

</div>
