<?php

namespace app\components;

use yii\base\Component;

class EngDis extends Component
{
    public static function convert($name)
    {
        $EngDisMap = [
            'ताप्लेजुङ्ग' => 'Taplejung',
            'पाँचथर' => 'Panchthar',
            'ईलाम' => 'Ilam',
            'झापा' => 'Jhapa',
            'संखुवासभा' => 'Sankhuwasabha',
            'तेह्रथुम' => 'Tehrathum',
            'भोजपुर' => 'Bhojpur',
            'धनकुटा' => 'Dhankuta',
            'मोरङ' => 'Morang',
            'सुनसरी' => 'Sunsari',
            'सोलुखुम्बु' => 'Solukhumbu',
            'खोटाङ' => 'Khotang',
            'ओखलढुङ्गा' => 'Okhaldhunga',
            'उदयपुर' => 'Udaypur',
            'सप्तरी' => 'Saptari',
            'सिराहा' => 'Siraha',
            'दोलखा' => 'Dolakha',
            'रामेछाप' => 'Ramechhap',
            'सिन्धुली' => 'Sindhuli',
            'धनुषा' => 'Dhanusha',
            'महोत्तरी' => 'Mahottari',
            'सर्लाही' => 'Sarlahi',
            'रसुवा' => 'Rasuwa',
            'धादिङ' => 'Dhading',
            'नुवाकोट' => 'Nuwakot',
            'काठमांडौ' => 'Kathmandu',
            'भक्तपुर' => 'Bhaktapur',
            'ललितपुर' => 'Lalitpur',
            'काभ्रेपलान्चोक' => 'Kavrepalanchok',
            'सिन्धुपाल्चोक' => 'Sindhupalanchok',
            'मकवानपुर' => 'Makwanpur',
            'रौतहट' => 'Rautahat',
            'बारा' => 'Bara',
            'पर्सा' => 'Parsa',
            'चितवन' => 'Chitwan',
            'गोरखा' => 'Gorkha',
            'मनाङ' => 'Manang',
            'लम्जुङ्ग' => 'Lamjung',
            'कास्की' => 'Kaski',
            'तनँह' => 'Tanahun',
            'स्याङ्गजा' => 'Syangja',
            'गुल्मी' => 'Gulmi',
            'पाल्पा' => 'Palpa',
            'अर्घाखाची' => 'Arghakhanchi',
            'नवलपरासी(बर्दाघाट सुस्ता पश्चिम)' => 'Nawalparasi(Bardaghat Susta Paschim)',
            'रुपन्देही' => 'Rupandehi',
            'कपिलवस्तु' => 'Kapilvastu',
            'मुस्ताङ' => 'Mustang',
            'म्याग्दी' => 'Myagdi',
            'बाग्लुङ' => 'Baglung',
            'पर्वत' => 'Parbat',
            'रुकुम(पश्चिम भाग)' => 'Rukum(Paschim Bhag)',
            'रोल्पा' => 'Rolpa',
            'प्यूठान' => 'Pyuthan',
            'सल्यान' => 'Salyan',
            'दाङ' => 'Dang',
            'डोल्पा' => 'Dolpa',
            'मुगु' => 'Mugu',
            'जुम्ला' => 'Jumla',
            'कालिकोट' => 'Kalikot',
            'हुम्ला' => 'Humla',
            'जाजरकोट' => 'Jajarkot',
            'दैलेख' => 'Dailekh',
            'सुर्खेत' => 'Surkhet',
            'बाँके' => 'Banke',
            'बर्दिया' => 'Bardiya',
            'बाजुरा' => 'Bajura',
            'अछाम' => 'Achham',
            'बझाङ्ग' => 'Bajhang',
            'डोटी' => 'Doti',
            'कैलाली' => 'Kailali',
            'दार्चुला' => 'Darchula',
            'बैतडी' => 'Baitadi',
            'डडेलधुरा' => 'Dadeldhura',
            'कन्चनपुर' => 'Kanchanpur',
            'नवलपरासी(बर्दाघाट सुस्ता पूर्व)' => 'Nawalparasi(Bardaghat Susta Purba)',
            'रुकुम(पूर्व भाग)' => 'Rukum(Purba Bhag)',

        ];

        return isset($EngDisMap[$name]) ? $EngDisMap[$name] : $name;
    }
}
